## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# working directory (required):
workdir: "/media/data/Sid/Promethian/Thalamus"

# prefix of all output files (optional; default = "sample")
sample_name: "Thalamus"

# reference genome (required)
genome: "/media/data/Sid/Annotation/Homo_sapiens.GRCh38.dna.primary_assembly_mod.fa"

# ONS reads in fastq format
reads_fastq: "/media/data/Emil/Human_brain_direct_cDNA/Thalamus_PAG09926/Thalamus_PAG09926_pass.fastq"

# threads (default = 30)
threads: 20

# input annotation data required for sqanti (required)
# make sure the contig names in the annotation matches the input SAM file
gtf: "/media/data/Emil/references/gencode.v38.annotation.gtf"
