## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# working directory (required):
workdir: ""

# prefix of all output files (optional; default = "sample")
sample_name: ""

# reference genome as fasta (required)
genome: ""

# ONT reads in fastq format
reads_fastq: ""

# threads (default = 30)
threads: 30

# input annotation data required for sqanti (required)
# make sure the contig names in the annotation matches the input SAM file
gtf: ""
